---
name: Deploy coffee app inside a container

on:
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - run: |
        echo The PR was merged
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Login to Docker Hub in self-hosted runner
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./coffee-project/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/coffee-project:latest
    - name: Login to Docker Hub in remote server
      run: ssh kkheni@${{ secrets.PRODUCTION_IP }} "sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}"
    - name: Stop coffee container
      run: ssh kkheni@${{ secrets.PRODUCTION_IP }} "sudo docker stop coffee-project"
    - name: Remove coffee container
      run: ssh kkheni@${{ secrets.PRODUCTION_IP }} "sudo docker rm coffee-project"
    - name: Pull new image
      run: ssh kkheni@${{ secrets.PRODUCTION_IP }} "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/coffee-project:latest"
    - name: Start new container
      run: ssh kkheni@${{ secrets.PRODUCTION_IP }} "sudo docker run -d --name coffee-project -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/coffee-project:latest"