name: Lint Node.js and ansible playbook
on: push
jobs:
  lint-Nodejs:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
#       # - name: Linter
#       #   uses: super-linter/super-linter/slim@v5
#       - name: Echo Something
#         run: echo "Hello, GitHub Actions!"
